export function initVerify() {
  const verifyContainer = document.getElementById('verify-container');
  if (!verifyContainer) return;

  // Create the verify UI
  verifyContainer.innerHTML = `
    <!-- Marketing Content -->
    <div id="marketing">
      <h2>carbon copy originals</h2>
      <p>we take what works and make it extraordinary.</p>
      <p>each garment contains a unique pattern generated by its code.</p>
      <p>can you crack the pattern system?</p>
      <a href="https://carboncopyoriginals.com">visit the shop</a>
    </div>

    <div id="verify-section">
      <h2>verify authenticity</h2>
      <p>enter your verification salt to generate your certificate.</p>
      <input type="text" id="salt-input" placeholder="enter verification salt" maxlength="12">
      <button onclick="verify()">verify</button>
      <div id="error"></div>

      <!-- Success Message and Certificate Container -->
      <div id="success-container">
        <div>
          <p>verification successful</p>
          <p>code: <span id="short-code"></span></p>
          <p>№<span id="unit-number"></span></p>
        </div>
        <div id="certificate"></div>
        <button onclick="downloadSVG()">download certificate</button>
      </div>
    </div>
  `;

  // Add styles
  const style = document.createElement('style');
  style.textContent = `
    #verify-container {
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
      font-family: 'Times New Roman', serif;
      color: #3856DD;
      text-align: center;
    }

    #verify-container h2 {
      font-weight: normal;
      font-size: 24px;
      margin: 0 0 20px;
      text-transform: lowercase;
    }

    #verify-container p {
      margin: 0 0 15px;
      opacity: 0.8;
    }

    #verify-container a {
      display: inline-block;
      padding: 15px 30px;
      background: #3856DD;
      color: #FFF6F0;
      text-decoration: none;
      text-transform: lowercase;
    }

    #verify-section {
      margin-top: 40px;
    }

    #salt-input {
      width: 100%;
      padding: 15px;
      margin: 10px 0;
      background: transparent;
      border: 2px solid #3856DD;
      color: #3856DD;
      font-family: 'Times New Roman', serif;
      font-size: 16px;
      text-align: center;
    }

    #verify-container button {
      width: 100%;
      padding: 15px;
      background: #3856DD;
      color: #FFF6F0;
      border: none;
      font-family: 'Times New Roman', serif;
      font-size: 16px;
      cursor: pointer;
      margin-top: 10px;
      text-transform: lowercase;
    }

    #error {
      color: #FF4444;
      margin-top: 10px;
      display: none;
    }

    #success-container {
      display: none;
      margin: 30px 0;
    }

    #success-container > div {
      margin: 30px 0;
      padding: 15px;
      border: 2px solid #3856DD;
    }
  `;
  document.head.appendChild(style);

  // Add verification functionality
  window.verify = async function() {
    const salt = document.getElementById('salt-input').value.toUpperCase();
    const urlParams = new URLSearchParams(window.location.search);
    const code = urlParams.get('code');
    const error = document.getElementById('error');
    const successContainer = document.getElementById('success-container');
    const certificate = document.getElementById('certificate');
    const marketing = document.getElementById('marketing');
    const shortCode = document.getElementById('short-code');

    if (salt.length !== 12) {
      error.textContent = 'please enter a valid 12-character salt';
      error.style.display = 'block';
      successContainer.style.display = 'none';
      return;
    }

    try {
      const response = await fetch('https://cco-six.vercel.app/api/verify', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          code,
          salt,
          mode: 'verify'
        })
      });

      const data = await response.json();

      if (data.valid) {
        certificate.innerHTML = data.certificate;
        successContainer.style.display = 'block';
        shortCode.textContent = code;
        document.getElementById('unit-number').textContent = String(data.unitNumber).padStart(4, '0');
        error.style.display = 'none';
        marketing.style.display = 'none';
      } else {
        error.textContent = 'invalid verification code';
        error.style.display = 'block';
        successContainer.style.display = 'none';
      }
    } catch (err) {
      error.textContent = 'verification error. please try again.';
      error.style.display = 'block';
      successContainer.style.display = 'none';
    }
  };

  // Add download functionality
  window.downloadSVG = function() {
    const svg = document.querySelector('#certificate svg');
    if (!svg) return;

    const blob = new Blob([svg.outerHTML], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'cco-certificate.svg';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Initialize verification if code is present
  const code = new URLSearchParams(window.location.search).get('code');
  const verifySection = document.getElementById('verify-section');
  const marketing = document.getElementById('marketing');

  if (!code) {
    verifySection.style.display = 'none';
  }
}